### ISSUE TITLE
Plan out Pass Past 98

### ISSUE THREAD

**Issue by Toxicable** [Toxicable/PassPast#42]
This task will include planning out, creating milestones and associating issues for the new application.
The stacks looks like it will be
Angular 2
ASP.NET Web Api, Signal R and SQL Server or FireBase  --needs to be decided on

-Continue to use FB/Google auth - setup SPA login flow
-use markdown for comments (https://www.npmjs.com/package/angular2-markdown)
-remove ability to make course and papers
-allow exams to be made but only with specific fomats
-use some sort of symbol-color combination to identity users in comments
-setup a beta.passpast.net domain for new website

**Comment by Toxicable** [comment]
-Continue to use FB/Google auth - setup SPA login flow

**Comment by Millyy** [comment]
-Avoid supergluing bouncy balls to pixels
-Mostly just make every vote and comment not refresh the page
-Change how comments are displayed, not responsive, no way of telling which question's comment button you clicked (just add Comments: Question1 or something)
-I don't think tagging which users wrote which comment/made which exam works
-Change submit/cancel buttons to be more in theme
-See if there's a way to access the University's current courses list - add as drop down instead of text box
